name: Test

on:
  push:
  pull_request:
  schedule:
    - cron:  '15 4 * * *'
  workflow_dispatch:

jobs:
  macos:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        brew install ccache libuv
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pylint
    - name: Build C extension
      run: |
        make c-extension -j 4
    - name: Test
      run: |
        make test-parallel -j 4

  cygwin:
    runs-on: windows-latest
    if: ${{github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'}}

    steps:
    - uses: actions/checkout@v1
    - name: Test
      run: |
        ./.github/workflows/cygwin.bat

  linux-test:
    runs-on: ubuntu-20.04
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8, 3.9 '3.10']

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -qq ccache libuv1-dev -y
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pylint
    - name: Build C extension
      run: |
        make c-extension -j 4
    - name: Lib
      run: |
        make -C mys/lib/test -j 4
    - name: Test
      run: |
        make test-parallel -j 2
        env MYS="PYTHONPATH=$(pwd) python3 -m mys" PYTHONPATH=$(pwd)/mys/pygments python3 -m unittest -k jobserver

  linux-examples:
    runs-on: ubuntu-20.04
    if: ${{github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags')}}

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -qq ccache libuv1-dev -y
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Build C extension
      run: |
        make c-extension -j 4
    - name: Examples
      run: |
        make -C examples -j 4

  linux-install-and-no-ccache:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -qq libuv1-dev -y
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Install
      run: |
        make test-install

  tools:
    runs-on: ubuntu-20.04
    if: ${{github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags')}}

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -qq ccache libuv1-dev -y
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Build C extension
      run: |
        make c-extension -j 4
    - name: Generate parser
      run: |
        make generate-parser

  lint:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint==2.12.2
        pip install -r requirements.txt
    - name: Lint
      run: |
        make lint

  style:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Style
      run: |
        make style
        git diff --quiet

  docs:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Build C extension
      run: |
        make c-extension -j 4
    - name: Build documentation
      run: |
        make docs

  release:
    needs: [macos, linux-test, linux-examples, linux-install-and-no-ccache, tools, lint, style, docs]
    runs-on: ubuntu-20.04
    if: startsWith(github.ref, 'refs/tags')

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install pypa/build
      run: |
        python -m pip install build --user
    - name: Build a binary wheel and a source tarball
      run: |
        git clean -dfx
        python -m build --sdist --outdir dist/ .
    - name: Publish distribution 📦 to PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        skip_existing: true
        password: ${{secrets.pypi_password}}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Build C extension
      run: |
        make c-extension -j 4
    - name: Publish release to mys-lang.org
      run: |
        make publish PUBLISH_TOKEN=${{secrets.publish_token}}
